### ISSUE TITLE
Manual override lights with only an On/Off state

### ISSUE THREAD

**Issue by donnyvangulik** [dgrnbrg/appdaemon-configs#3]
Hi David, 

Using your lights.py with great success here in my setup. However, I am running into a limitation with lights that only have an On/Off state (such as shelly1) and trying to use the manual override. 

I have tried to adjust the code, but have not been successful. 

So the issue is: 

Light is being controlled by lights.py > light switch is controlled at the wall > state changes (also in HA) > light_state_light_X remains 'off' > scripts takes back control of light. 

Could you point me in the right direction?

Best regards,

Donny

**Comment by dgrnbrg** [comment]
I'm really glad to hear that!

Just to clarify, does the manual control fail to take effect only when turning a on/off light to `on` manually? Or does manual control fail regardless when a wall switch is used?

Also, does using a wall switch work when the light is dimmable/temp adjustable? If so, what brand/model of switch are you using?

(these questions are to help me guess which events are being observed, and what I might be incorrectly ignoring)

**Comment by donnyvangulik** [comment]
Thank you for your reply! 

It fails regardless when a wall switch is used. Just checked, when the automation has been set to manual (through HA dashboard) turning on or off the switch does not affect the automation in any way. 

The wall switches are are working for dimmable lights such as Shelly Dimmer2 and ESPHome switches which are setup as detached switch controlling Zigbee lighting are working great (as long as I use the individual lights in the automation and avoid groups). The ones which are not triggering the 'manual' mode are Shelly1 relays with an attached switch (mix of momentary and edge)

Thanks for your support!! If you need any additional information, let me know.

**Comment by dgrnbrg** [comment]
So, here's my hypothesis: the lights which are working correctly are generating `call_service` events in homeassistant, and the ones that don't work correctly are operating without generating the `call_service` event because they're entirely local to the shelly.

Does that seem to match/make sense given what you're doing?

If so, I have a couple solutions in mind...

**Comment by donnyvangulik** [comment]
Yes, that seems to be the case. They do get updated in HA after pressing the wall switch, but it does not show the call_service light.turn_on / off in the log. 

Thanks again :)

**Comment by dgrnbrg** [comment]
So, there's 2 approaches:

One thing we could do is `listen_state` to the light itself, and write some code to handle detecting changes (probably just invoke `service_snoop` with a fake call). This `listen_state` could be supressed for ~1s after a `call_service` (or it could remember the recent service calls and ignore state changes that match), so that if the state changed without a service call, we know it was from the light itself.

The other thing we could do is make all the wall switches generate call_service events by running them in detached mode.

I think that the first solution is probably the correct solution, but it'll be a little tricky to avoid infinite loops, and I except other weird things will crop up. I'm happy to review, or implement this (but that may take me a bit to find the time).

**Comment by donnyvangulik** [comment]
Thanks! The first option, sound like something that will work for my use case. Will let you know if I can crop something up that works :) Again, very much appreciated.

**Comment by donnyvangulik** [comment]
Thanks again for taking your time to guide me. The solution that seems to be working for now is a separate app. 
At first I tried the listen_state, but this resulted in 700k callbacks in 24hrs. So now I am making use of supress_callback option, and it is much more efficient. Seems to be working fine now :) 

```python
import appdaemon.plugins.hass.hassapi as hass


class LightMonitorApp(hass.Hass):
    def initialize(self):
        self.monitored_lights = self.args.get("monitored_lights", [])
        self.suppress_callback = False

        for light_entity in self.monitored_lights:
            self.listen_state(self.light_state_changed, light_entity)

    def light_state_changed(self, entity, attribute, old, new, kwargs):
        if self.suppress_callback:
            self.log("Callback suppressed for entity: {}".format(entity))
            return

        if new == "on":
            self.call_service("light/turn_on", entity_id=entity)
        elif new == "off":
            self.call_service("light/turn_off", entity_id=entity)

    def on_service_call(self, event_name, data, kwargs):
        # Check if the service call originated from this app
        if data.get("service") and data["service"].lower().startswith("lightmonitorapp"):
            self.suppress_callback = True

            # Reset the suppress flag after 1 second
            self.run_in(self.reset_callback_suppression, 1)

    def reset_callback_suppression(self, kwargs):
        self.suppress_callback = False
        self.log("Callback suppression reset")

```

The .yaml entry

```yaml
light_monitor_app:
  module: light_monitor_app
  class: LightMonitorApp
  monitored_lights:
    - light.kitchen
    - light.living_room
    - light.bedroom
```

Can you also test if this is working correctly?
